    # wrangler.toml
    name = "dashboard-worker" # Replace with your desired Worker name
    main = "workers/index.ts" # Path to your Worker file
    compatibility_date = "2023-01-01" # Adjust as needed

# [site]
# bucket = "./frontend/dist"
assets = { binding = "ASSETS", directory = "./frontend/dist" }

[vars]
VITE_SUPABASE_URL= 'https://crqbazcsrncvbnapuxcp.supabase.co'
VITE_SUPABASE_ANON_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNycWJhemNzcm5jdmJuYXB1eGNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzMDk1MDYsImV4cCI6MjA3Njg4NTUwNn0.AQdRVvPqeK8l8NtTwhZhXKnjPIIcv_4dRU-bSZkVPs8'
